version: '3.8'

services:
  db:
    build:
      context: db
      dockerfile: ./Dockerfile
    ports:
      - "3306:3306"
    volumes:
      - spring-data:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - "8282:8080"
  web:
    build:
      context: web
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://db:3306/smarthome
      SPRING_DATASOURCE_USERNAME: smarthome
      SPRING_DATASOURCE_PASSWORD: smarthome
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.mariadb.jdbc.Driver
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.MariaDBDialect
      SPRING_JPA_HIBERNATE_DDL_AUTO: create
      SPRING_DATA_REST_BASE_PATH: /api


volumes:
  spring-data: