version: '3.8'

services:
  web:
    build:
      context: web
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"

    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://vsgate-s1.dei.isep.ipp.pt:11185/smarthome
      SPRING_DATASOURCE_USERNAME: smarthome
      SPRING_DATASOURCE_PASSWORD: "askforpassword"
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
      SPRING_JPA_HIBERNATE_DDL_AUTO: create

volumes:
  spring-data: