name: Build Project and Run Tests

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.1
      
      - name: Set up JDK 17
        uses: actions/setup-java@v4.2.1
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'maven'
      
      - name: Set up Pitest Caching Folder
        run: mkdir -p target/.pitest-cache

      - name: Cache Maven packages
        uses: actions/cache@v4.0.2
        with:
          path: ~/.m2
          #key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          key: ${{ runner.os }}-m2
          restore-keys: ${{ runner.os }}-m2
      
      - name: Cache Pitest reports
        uses: actions/cache@v4.0.2
        with:
          path: target/.pitest-cache
          key: ${{ runner.os }}-pitest
          restore-keys: ${{ runner.os }}-pitest
          
      - name: Build with Maven
        run: mvn -B --file pom.xml test jacoco:report verify
        
#      - name: Test with Maven
#        run: mvn -B test --file pom.xml
